Update README.md
ustaxcourt/2024-digital-environment-rfi pull request #1
Opened 2024-12-30 19:56 UTC by jhansentc

updated the RFI with new due date.

2025-01-02 22:09 UTC, jimlerza requested changes

2025-01-02 22:09 UTC, jimlerza commented on README.md
> +See enclosed [PDF with Request for Information Document](https://ustaxcourt-my.sharepoint.com/:b:/r/personal/jenna_hansen_ustaxcourt_gov/Documents/Attachments/USTC%20RFI%20Digital%20Environment%20202
This was previously a link to a file contained in this repository.

With this change, only Court employees that are logged into their Court account will be able to view the document this link is pointing to.

I think you probably need to include the updated file in this PR such that it overwrites the other copy in this repo, and then not change line 5 at all. Unless the point of this diff is to make that file inaccessible to non-Court users?

2025-01-02 22:15 UTC, jhansentc commented on README.md
> +See enclosed [PDF with Request for Information Document](https://ustaxcourt-my.sharepoint.com/:b:/r/personal/jenna_hansen_ustaxcourt_gov/Documents/Attachments/USTC%20RFI%20Digital%20Environment%20202
Gotcha. Let me check with Mustafa.

2025-01-03 15:13 UTC, jimlerza approved these changes

2025-01-03 15:13 UTC, merged